pool:
  vmImage: 'Ubuntu 16.04'
#Your build pipeline references a secret variable named ‘sp_username’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘sp_password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

# Azure Pipeline Definition for Infrastructure Deployment
name: Deploy Sandbox Infrastructure

# Trigger on changes in the infrastructure folder and on the master branch                      
trigger:
  branches:
    include:
    - master

  paths:
    include:
    - /*
    - infra-as-code/*

parameters:
- name: baseName
  type: string
  default: povl
- name: vnet
  type: string
  default: hdivnet
- name: addressSpaces
  type: string
  default: 10.3.0.0/16
- name: subnet0
  type: string
  default: default
- name: subnet0addr
  type: string
  default: 10.3.0.0/24
- name: subnet1
  type: string
  default: second
- name: subnet1addr
  type: string
  default: 10.3.1.0/24
- name: hdiBaseName
  type: string
  default: libor
- name: hdiHadoopLogin
  type: string
  default: kadim
- name: hdiHadoopPassword
  type: securestring
  default: Password1.!!
- name: hdiVersion
  type: string
  default: 3.6
- name: clusterWorkerCountMin
  type: int
  default: 5
- name: clusterWorkerCountMax
  type: int
  default: 10
- name: clusterWorkerSize
  type: string
  default: "Standard_F4"
- name: clusterKind
  type: string
  default: "HADOOP"
- name: sshUserName
  type: string
  default: "sshuser"
- name: environment
  type: string
  default: dev
  values: 
  - test
  - dev
- name: location
  type: string
  default: eastus
- name: serviceConnection
  type: string
  default: pavle-svc
- name: workspacename
  type: string
  default: mls
- name: storageaccount
  type: string
  default: sa
- name: secretname
  type: string
  default: bentleysecret
- name: datastore
  type: string
  default: ds
- name: containername
  type: string
  default: raw


stages:
- stage: BuildInfra
  displayName: 'Build Azure Infrastructure'
  jobs:
  - template: infra-as-code/azure-infra.yml
    parameters:
      baseName: ${{ parameters.baseName }}
      environment: ${{ parameters.environment }}
      location: ${{ parameters.location }}
      storageaccount: ${{ parameters.storageaccount }}
      containername: ${{ parameters.containername }}
      serviceConnection:  ${{ parameters.serviceConnection }}



