pool:
  vmImage: 'Ubuntu 16.04'
#Your build pipeline references a secret variable named ‘sp_username’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972
#Your build pipeline references a secret variable named ‘sp_password’. Create or edit the build pipeline for this YAML file, define the variable on the Variables tab, and then select the option to make it secret. See https://go.microsoft.com/fwlink/?linkid=865972

# Azure Pipeline Definition for Infrastructure Deployment
name: Deploy Sandbox Infrastructure

# Trigger on changes in the infrastructure folder and on the master branch                      
trigger:
  branches:
    include:
    - main

  paths:
    include:
    - /*
    - infra-as-code/*

parameters:
- name: baseName
  type: string
  default: dignex
- name: environment
  type: string
  default: sbx
  values: 
  - test
  - sbx
  - sdbx
- name: location
  type: string
  default: eastus
- name: serviceConnection
  type: string
  default: clientdemo
- name: storageaccount
  type: string
  default: sfdcsa
- name: containername
  type: string
  default: raw
- name: hadoopBaseName
  type: string
  default: hdp
- name: sparkBaseName
  type: string
  default: spr
- name: hdiHadoopLogin
  type: string
  default: kadim
- name: hdiHadoopPassword
  type: string
  default: Password1.!!
- name: hdiVersion
  type: string
  default: 3.6
- name: clusterWorkerCountMin
  type: number
  default: 5
- name: clusterWorkerCountMax
  type: number
  default: 10
- name: clusterWorkerSize
  type: string
  default: "Standard_F4"
- name: clusterKind
  type: string
  default: "HADOOP"
  values: 
  - "HADOOP"
  - "SPARK"
- name: clusterKind2
  default: "SPARK"
  values: 
  - "HADOOP"
  - "SPARK"
- name: sshUserName
  type: string
  default: "sshuser"
- name: vnet
  type: string
  default: hdivnet
- name: addressSpaces
  type: string
  default: 10.3.0.0/16
- name: subnet0
  type: string
  default: datasubnet
- name: subnet0addr
  type: string
  default: 10.3.0.0/24
- name: subnet1
  type: string
  default: appsubnet
- name: subnet1addr
  type: string
  default: 10.3.1.0/24
- name: subnet2
  type: string
  default: aads
- name: subnet2addr
  type: string
  default: 10.3.2.0/24
- name: appnodeName
  type: string
  default: appnode
- name: computenodeName
  type: string
  default: computenode
- name: nsgBase
  type: string
  default: nsg
- name: nicBaseName
  type: string
  default: nic
- name: vmsize
  type: string
  default: "Standard_D2_V2"
- name: msqlserverName
  type: string
  default: zalsql
- name: msqlskuCapacity
  type: number
  default: 2
- name: msqlskuName
  type: string
  default: "GP_Gen5_2"
- name: sqlSkuName
  type: string
  default: "GP_Gen5"
- name: msqlskuSizeMB
  type: number
  default: 512000
- name: msqlskuTier
  type: string
  default: "GeneralPurpose"
- name: msqlskuFamily
  type: string
  default: "Gen5"
- name: sqlName
  type: string
  default: midb



stages:
- stage: BuildInfra
  displayName: 'Build Azure Infrastructure'
  jobs:
  - template: infra-as-code/azure-infra.yml
    parameters:
      baseName: ${{ parameters.baseName }}
      environment: ${{ parameters.environment }}
      location: ${{ parameters.location }}
      serviceConnection:  ${{ parameters.serviceConnection }}
      storageaccount: ${{ parameters.storageaccount }}
      containername: ${{ parameters.containername }}
      hadoopBaseName: ${{ parameters.hadoopBaseName }}
      sparkBaseName: ${{ parameters.sparkBaseName}}
      hdiHadoopLogin: ${{ parameters.hdiHadoopLogin }}
      hdiHadoopPassword: ${{ parameters.hdiHadoopPassword }}
      hdiVersion: ${{ parameters.hdiVersion }}
      clusterWorkerCountMin: ${{ parameters.clusterWorkerCountMin }}
      clusterWorkerCountMax: ${{ parameters.clusterWorkerCountMax }}
      clusterWorkerSize: ${{ parameters.clusterWorkerSize }}
      clusterKind: ${{ parameters.clusterKind }}
      clusterKind2: ${{ parameters.clusterKind2 }}
      sshUserName: ${{ parameters.sshUserName }}
      vnet: ${{ parameters.vnet }}
      addressSpaces: ${{ parameters.addressSpaces }}
      subnet0: ${{ parameters.subnet0 }}
      subnet0addr: ${{ parameters.subnet0addr }}
      subnet1: ${{ parameters.subnet1 }}
      subnet1addr: ${{ parameters.subnet1addr }}
      subnet2: ${{ parameters.subnet2 }}
      subnet2addr: ${{ parameters.subnet2addr }}
      appnodeName: ${{ parameters.appnodeName }}
      computenodeName: ${{ parameters.computenodeName }}
      nsgBase: ${{ parameters.nsgBase }}
      nicBaseName: ${{ parameters.nicBaseName }}
      vmsize: ${{ parameters.vmsize }}
      msqlserverName: ${{ parameters.msqlserverName }}
      msqlskuCapacity: ${{ parameters.msqlskuCapacity }}
      msqlskuName: ${{ parameters.msqlskuName }}
      sqlSkuName: ${{ parameters.sqlSkuName }}
      msqlskuSizeMB: ${{ parameters.msqlskuSizeMB }}
      msqlskuTier: ${{ parameters.msqlskuTier }}
      msqlskuFamily: ${{ parameters.msqlskuFamily }}
      sqlName: ${{ parameters.sqlName }}






