# Continuous Integration (CI) pipeline that orchestrates the training, evaluation, registration, deployment, and testing of the tchmielMLOps model.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest
   
variables:
  - group: AzureKeyVaultSecrets

parameters:
- name: baseName
  type: string
- name: environment
  type: string
- name: location
  type: string
- name: serviceConnection
  type: string
- name: workspacename
  type: string
- name: computename
  type: string
- name: amlenv
  type: string

variables:
- name: RESOURCEGROUP_NAME
  value: rg-${{ parameters.baseName }}-${{ parameters.environment }}
- name: resourceGroupLocation
  value: ${{ parameters.location }}  
- name: WORKSPACE_NAME
  value: ${{ parameters.baseName }}-${{ parameters.workspacename }}-${{ parameters.environment }}
- name: CLUSTER_NAME
  value: ${{ parameters.computename }}
- name: AML_ENVIRONMENT_NAME
  value: ${{ parameters.amlenv }}
- name: BLOBSTORENAME
  value: train${{ parameters-baseName }}
- name: DATASETDS
  value: pavfantasyfootball
- name: CONTNAME
  value: bentleyhack

stages:
- stage: 'PaC'
  displayName: 'Pipeline Deploy'
  condition: 
  jobs:
  - job: "Setup of Pipeline"
    displayName: "Pipeline Setup "
    container: mlops
    timeoutInMinutes: 0
    steps:
      - script: |
          python build_pipeline.py
        displayName: 'Pipeline Environment'
        env:
          TENANT_ID: $(sptenant)
          SPN_ID: $(spidentity)
          SPN_PASSWORD: $(spsecret)
          AML_WORKSPACE_NAME: $(WORKSPACE_NAME)
          AML_ENVIRONMENT_NAME: $(AML_ENVIRONMENT_NAME)
          RESOURCE_GROUP: $(RESOURCEGROUP_NAME)
          COMPUTE_NAME: $(CLUSTER_NAME)
          SUBSCRIPTION_ID: $(subscriptionid)
          BLOBSTORENAME: $(BLOBSTORENAME)
          DATASETDS: $(DATASETDS)
          CONTNAME: $(CONTNAME)
          ACCTKEY: $(saKey)

